### ISSUE TITLE
Flex-direction column

### ISSUE THREAD

**Issue by ryanmclaughlin** [colbycheeze/bluegrid#11]
I can see how it may have been intentional to omit something like this a flexbox grid system, but what do you think about support for switching a to `flex-direction: column` of a `row`? Mostly curious as I've come across several cases where this would've been very helpful while keeping things simple.

**Comment by colbycheeze** [comment]
one way to do this is by setting an offset to push the contents off at a certain breakpoint such as:

``` sass
  .item-1 {
    @include column(6);
    @include breakpoint(1px 960px) {
      @include offset(6, right);
    }
  }
  .item-2 { @include column(6); }
```

There is also a way to change flex-direction from row to column when assigning it here:
`@include row(column)`
that might not be what you want in this case though.

**Comment by ryanmclaughlin** [comment]
I wasn't aware of the latter one. `@include row(column)` Thanks!
